### ISSUE TITLE
fsockopen() Failed to parse address

### ISSUE THREAD

**Issue by Chief88** [centraldesktop/php-stomp#16]
The following occurred
vendor/centraldesktop/stomp/src/CentralDesktop/Stomp/Connection.php:142
In PHP 7.1.4 @fsockopen() return false due to the fact that `Warning: fsockopen(): unable to connect to tcp://127.0.0.1:61613:61613 (Failed to parse address "127.0.0.1:61613:61613")`
$brokerUri should not contain the port

**Comment by dstevenson** [comment]
`$brokerUri` comes directly from what you pass into your `ConnectionFactory\FactoryI` constructor, which should contain a port. Can you double check your arguments to make sure you don't have the port repeated?

`vendor/centraldesktop/stomp/src/CentralDesktop/Stomp/Connection.php` runs the `$brokerUri` through a `parse_url` before passing it into the `fsockopen` to split the host from the port accordingly.

e.g.

```
$host = "tcp://127.0.0.1:61613";
$factory = new CentralDesktop\Stomp\ConnectionFactory\Simple($host);
$stomp = new CentralDesktop\Stomp\Connection($factory);
```

**Comment by dstevenson** [comment]
@Chief88 This actually is a bug, sorry. It looks like in PHP versions < 7.0.18 and < 7.1.4 the stream functions incorrectly accepted a hostname with a port. The bug can be found here: https://bugs.php.net/bug.php?id=74216

This was patched and we were running an older version, so that's why we were unable to detect the issue. I am making the change here to fix this.
